### ISSUE TITLE
[General]: Proposal for branch to collect BB changes

### ISSUE THREAD

**Issue by LS0205** [CSA-FEDERATE/Proposed-BuildingBlocks#19]
### Contact Details

lukas.springer@avl.com

### Problem Description

In the future there will be more proposals for updating and adding BBs. As it is not practical to open a new branch for every minor change I suggest to create one branch which collects all BB updates within a set timeframe. The branch has to reviewed and merged to the main branch periodically

**Comment by prillerp** [comment]
for now we prepare to remain on "one issue per branch", to make decision easier and avoid blocking / conflicts

**Comment by prillerp** [comment]
closed.
