### ISSUE TITLE
[General]:

### ISSUE THREAD

**Issue by jankubovy** [CSA-FEDERATE/Proposed-BuildingBlocks#37]
### Problem Description

In our WP4 meeting we had an interesting discussion about improving the BB structure by adding a state to mapped OSS projects:

**State (+ date of last change)**

- Incubating (no code yet) 
- Implementation started
- First public release available
- Used in production by 1 OEM
- Used in production by >1 OEM
- Abandoned

Any thoughts?

**Comment by LS0205** [comment]
added in PR #41
