### ISSUE TITLE
[General]:Add "System Context" to BB template

### ISSUE THREAD

**Issue by prillerp** [CSA-FEDERATE/Proposed-BuildingBlocks#39]
### Contact Details

peter.priller@avl.com

### Problem Description

We suggest to add one **new context property** to better describe the underlying requirement to run the BB (OS/framework), e.g. but not limited to
* AGL
* QNX
* ROS-based
* container runtime
* web assembly
* web service

This shall NOT replicate the full dependencies list and detailed runtime environment description - this is in the implementation project only.
However, this attribute should give a first impression of the BB only.

**Comment by LS0205** [comment]
added in PR #41
